adminbase/urls.py
'''
	admin urls
'''
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	#admin에서 include로 바로 넘기기에 로그인 기능등 모든 기능은 dashboard에서 이루어져야 함
    url(r'^', include('dashboard.urls', namespace='dashboard')),
    url(r'^admin/', include(admin.site.urls)),
]

payments/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    # put your urls
    url(r'^$', login_required(views.PaymentManageView.show), name='managePaymentShow'),
    url(r'^search/$', login_required(views.PaymentManageView.search), name='managePaymentSearch'),  
    url(r'^inquire/$', login_required(views.PaymentManageView.inquire), name='managePaymentInquire'),  
    url(r'^create/$', login_required(views.PaymentManageView.create), name='managePaymentCreate'),
    url(r'^createForm/$', login_required(views.PaymentManageView.createForm), name='managePaymentCreateForm'),     
    url(r'^update/$', login_required(views.PaymentManageView.update), name='managePaymentUpdate'),
    url(r'^updateForm/$', login_required(views.PaymentManageView.updateForm), name='managePaymentUpdateForm'),
    url(r'^delete/$', login_required(views.PaymentManageView.delete), name='managePaymentDelete'),
    url(r'^deleteForm/$', login_required(views.PaymentManageView.deleteForm), name='managePaymentDeleteForm'),    
]

sales/urls.py
'''
    urls is to be connect view 
'''
from django.conf.urls import url
from . import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    # manage student urls
    url(r'^display/$', login_required(views.daySalesView.display), name="salesDisplay"),
    url(r'^display/makeDay/$', login_required(views.daySalesView.makeDay), name='salesCreateDay'),
    url(r'^display/inquire/$', login_required(views.daySalesView.inquire), name='salesInquire'),
    url(r'^display/monthSales/$', login_required(views.motnthSaleView.as_view()), name='monthSales'),
]

payments/models.py
from django.db import models
from students.models import Student
from django.utils import timezone

# Create your models here.
class Payment(models.Model):
	PAYMENT_CHOICE = (
		('카드','카드'),
		('현금','현금'),
	)
	PAYMENT_STATE = (
		('결제','결제'),
		('환불','환불'),
	)
	number = models.AutoField(primary_key=True, verbose_name="번호")	
	paymentDate = models.DateField(default=timezone.now, verbose_name="결제일")
	student = models.ForeignKey(Student, null=True, verbose_name="학생", on_delete=models.CASCADE)
	paymentType = models.CharField(max_length=6, choices=PAYMENT_CHOICE, default='카드', verbose_name="결제방식")
	paymentState = models.CharField(max_length=6, choices=PAYMENT_STATE, default='결제', verbose_name="결제상태")
	item = models.CharField(max_length=30, null=True, verbose_name="수업/상품")
	price = models.IntegerField(default=0, blank=True, verbose_name="가격")
	note = models.CharField(max_length=100, blank=True, default='', null=True, verbose_name="Memo")
	def __str__(self):
		return str(self.student)+'의 결제['+str(self.paymentDate)+']'

payments/forms.py
from django import forms
from .models import Payment
from lessons.models import Lesson


class PaymentForm(forms.ModelForm):
    item = forms.ModelChoiceField(queryset=Lesson.objects.all(), empty_label="Please select.", label="수업/상품")
    class Meta:
        model = Payment
        fields = ('number', 'paymentDate','paymentType', 'paymentState', 'student', 'item', 'price', 'note')

class PaymentUpdateForm(forms.ModelForm):
    class Meta:
        model = Payment
        fields = ('number', 'paymentDate', 'paymentType', 'paymentState', 'student', 'item', 'price', 'note')

payments/views.py
from django.views.generic import TemplateView

from django.shortcuts import render
from lessons.models import Lesson
from .models import Payment
from .forms import PaymentForm, PaymentUpdateForm
from django.template.loader import render_to_string
from students.models import Student
from students.forms import StudentSearchForm
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse		 	
from django.utils import timezone

class PaymentManageView(TemplateView):
	def show(request):
		return render(request, 'payments/managePayment.html', {})

	def search(request):
		if request.method == 'POST':
			html = {}
			student = Student.objects.filter(stname=request.POST['name'])
			html['form_is_valid'] = True
			html['student_list'] = render_to_string('payments/managePaymentStudentList.html', {'students':student},
				request=request)
			html['payment_list'] = render_to_string('payments/managePaymentPartialList.html', {},
				request=request)			
		else:
			html['form_is_valid'] = False
			html['student_list'] = render_to_string('payments/managePaymentStudentList.html', {}, request=request)
			html['payment_list'] = render_to_string('payments/managePaymentPartialList.html', {},
				request=request)			
		return JsonResponse(html)

	def savePaymentForm(template_name, form, request):
		html = {}
		if request.method == 'POST':
			if form.is_valid():
				payment = form.save(commit=False)
				lesson = Lesson.objects.get(item=str(form.cleaned_data['item']).split('[')[0])
				payment.item = lesson.item
				if form.cleaned_data['price'] == 0:
					payment.price = lesson.price
				else:
					payment.price = form.cleaned_data['price']
				payment.student = form.cleaned_data['student']
				payment.save()
				student = payment.student
				student.isPayday = 'PAYED'
				student.save()
				student.payment_set.add(payment)
				if payment.paymentState == '결제':
					lesson.student_set.add(student)
					lesson.save()
				else:
					student.lesson = None
					student.save()
				html['form_is_valid'] = True
				students = Student.objects.filter(stname=student.stname)
				payments = student.payment_set.all()
				html['student_list'] = render_to_string('payments/managePaymentStudentList.html',{'students':students})
				html['payment_list'] = render_to_string('payments/managePaymentPartialList.html',{'payments':payments})
			else:
				html['form_is_valid'] = False
		context = {'form':form}
		html['html_form'] = render_to_string(template_name, context,request=request)
		return JsonResponse(html)

	def savePaymentForm2(template_name, form, request, payment):
		html = {}
		if request.method == 'POST':
			if form.is_valid():
				payment = form.save(commit=False)
				lesson = Lesson.objects.get(item=str(form.cleaned_data['item']).split('[')[0])
				payment.item = lesson.item
				if form.cleaned_data['price'] == 0:
					payment.price = lesson.price
				else:
					payment.price = form.cleaned_data['price']
				payment.student = form.cleaned_data['student']
				payment.save()
				student = payment.student
				student.isPayday = 'PAYED'
				student.save()

				student.payment_set.update()
				if payment.paymentState == '결제':
					lesson.student_set.add(student)
					lesson.save()
				else:
					student.isPayday = 'UNPAY'
					student.lesson = None
					student.save()
				html['form_is_valid'] = True
				students = Student.objects.filter(stname=student.stname)
				payments = student.payment_set.all()
				html['student_list'] = render_to_string('payments/managePaymentStudentList.html',{'students':students})
				html['payment_list'] = render_to_string('payments/managePaymentPartialList.html',{'payments':payments})
			else:
				html['form_is_valid'] = False
		context = {'form':form,'payment':payment}
		html['html_form'] = render_to_string(template_name, context,request=request)
		return JsonResponse(html)
	def inquire(request):
		html = {}
		if request.method == 'POST':
			number = request.POST['number']
			student = Student.objects.get(number=number)
			payments = student.payment_set.all()
			students = Student.objects.filter(stname=student.stname)
			html['form_is_valid'] = True
			html['student_list'] = render_to_string('payments/managePaymentStudentList.html', {'students':students},
				request=request)
			html['payment_list'] = render_to_string('payments/managePaymentPartialList.html', {'payments':payments},
				request=request)
		return JsonResponse(html)

	def create(request):
		if request.method == 'POST':
			number = request.POST['number']
			student = Student.objects.get(number=number)
			form = PaymentForm(initial={'student': student,'paymentDate':timezone.localtime(timezone.now()).date()})
		# get url can't move student obj to payments obj so should put sutdent to payments	
		return PaymentManageView.savePaymentForm('payments/managePaymentPartialCreate.html', form, request)		
	
	def createForm(request):
		if request.method == 'POST':
			form = PaymentForm(request.POST)
		return PaymentManageView.savePaymentForm('payments/managePaymentPartialCreate.html', form, request)

	def update(request):
		if request.method == 'POST':
			number = request.POST['number']
			payment = Payment.objects.get(number=number)
			form = PaymentUpdateForm(instance=payment)
			return PaymentManageView.savePaymentForm2('payments/managePaymentPartialUpdate.html', form, request, payment)
	def updateForm(request):
		if request.method == 'POST':
			number = request.POST['number']
			payment = Payment.objects.get(number=number)
			form = PaymentUpdateForm(request.POST, instance=payment)
			return PaymentManageView.savePaymentForm2('payments/managePaymentPartialUpdate.html', form, request, payment)

	def delete(request):
		html = {}
		if request.method == 'POST':
			number = request.POST['number']
			payment = Payment.objects.get(number=number)
			context = {'payment':payment}
			html['html_form'] = render_to_string('payments/managePaymentPartialDelete.html', context, request=request)
			return JsonResponse(html)

	def deleteForm(request):
		html={}
		if request.method == 'POST':
			number = request.POST['number']
			payment = Payment.objects.get(number=number)
			student = payment.student
			payment.delete()
			html['form_is_valid'] = True
			payments = student.payment_set.all()
			students = Student.objects.filter(stname=student.stname)
			html['student_list'] = render_to_string('payments/managePaymentStudentList.html', {'students':students},
				request=request)
			html['payment_list'] = render_to_string('payments/managePaymentPartialList.html', {'payments':payments},
				request=request)
			return JsonResponse(html)		

templates/payments/managePayment.html
{% extends "dashboard/base.html" %}
{% load staticfiles %}

{% block extrahead %}
<!-- This is about datatable showing table search, pagenator -->
<!-- DataTables CSS -->
<link href="{% static 'bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.css' %}" rel="stylesheet">
<!-- DataTables Responsive CSS -->
<link href="{% static 'bower_components/datatables-responsive/css/dataTables.responsive.css' %}" rel="stylesheet">

{% endblock extrahead %}

{% block content %}
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">결제관리</h1>
    </div>

    
</div>

<div class="form-group input-group" id="div-student-search" style="width:30%">
    <input type="text" class="form-control input-student-name" placeholder="회원이름을 입력하세요">
        <span class="input-group-btn">
            <button type="button" class="btn btn-default js-student-search" url="{% url 'dashboard:managePaymentSearch' %}"><i class="fa fa-search"></i></button>
        </span>    
</div>

<div class="row" id="div-student">
    <div class="col-lg-7">
        <div class="box box-info">
            <div class="box-body table-responsive no-padding">       
                <div class="dataTable_wrapper">
                    <table class="table table-striped table-bordered table-hover" id="table-student" style="width:100%">
                        <thead>
                            <tr>
                                <th class="text-center" width="10%">회원번호</th>
                                <th class="text-center" width="8%">이름</th>
                                <th class="text-center" width="11%">연락처</th>
                                <th class="text-center" width="15%">학교</th>
                                <th class="text-center" width="5%">학년</th>
                                <th class="text-center" width="14%">/</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% include 'payments/managePaymentStudentList.html' %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">결제기록</h1>
    </div>
</div>

<div class="row" id="div-payment">
    <div class="col-lg-10">
        <div class="box box-warning">
            <div class="box-body table-responsive no-padding">       
                <div class="dataTable_wrapper">                   
                    <table class="table table-striped table-bordered table-hover" style="width:100%" id="table-payment">
                        <thead>
                            <tr>
                                <th class="text-center" width="2%">No.</th>
                                <th class="text-center" width="8%">일자</th>
                                <th class="text-center" width="7%">결제방식</th>
                                <th class="text-center" width="15%">수업/상품</th>
                                <th class="text-center" width="5%">가격</th>
                                <th class="text-center" width="15%">비고</th>
                                <th class="text-center" width="8%">/</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% include 'payments/managePaymentPartialList.html' %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modal-payment">
    <div class="modal-dialog">
        <div class="modal-content"></div>
    </div>
</div>
{% endblock content %}

{% block extrajs %}
<script src="{% static 'js/managePayment.js' %}"></script>
<!-- DataTables JavaScript -->
<script src="{% static 'bower_components/datatables/media/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js' %}"></script>

<!-- Page-Level Scripts - Tables - Use for reference -->
<script>
    $(document).ready(function() {
        $('#table-payment').DataTable({
            responsive: true,
            "columnDefs": [{
            "defaultContent": "-",
            "targets": "_all"
            }]            
        });

    });
</script>
{% endblock extrajs %}

templates/payments/managePaymentPartialCreate.html
{% load widget_tweaks %}
<form method="post" action="{% url 'dashboard:managePaymentCreateForm' %}" class="js-payment-register-form">
  {% csrf_token %}
  <div class="modal-header" >
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">결제등록</h4>
  </div>
  <div class="modal-body">
    {% for field in form %}
    <div class="form-group{% if field.errors %} has-error{% endif %}">
      <label for="{{ field.id_for_label }}">{{ field.label }}</label>
      {% render_field field class="form-control" %}
      {% for error in field.errors %}
      <p class="help-block">{{ error }}</p>
      {% endfor %}
    </div>
    {% endfor %}
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">취소</button>
    <button type="submit" class="btn btn-primary">등록</button>
  </div>
</form>

templates/payments/managePaymentPartialDelete.html
<form method="post" action="{% url 'dashboard:managePaymentDeleteForm' %}" class="js-payment-delete-form">
  {% csrf_token %}
  <div class="modal-header">
    <input class="hidden" name="number" value="{{payment.number}}">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">결제삭제</h4>
  </div>
  <div class="modal-body">
    <p class="lead">정말 삭제하시겠습니까?</p>
  </div>
  <div class="modal-footer">
    <button type="submit" class="btn btn-danger">예</button>
    <button type="button" class="btn btn-default" data-dismiss="modal">아니요</button>
  </div>
</form>

templates/payments/managePaymentPartialForm.html
{% load widget_tweaks %}

{% for field in form %}
  <div class="form-group{% if field.errors %} has-error{% endif %}">
    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
    {% render_field field class="form-control" %}
    {% for error in field.errors %}
      <p class="help-block">{{ error }}</p>
    {% endfor %}
  </div>
{% endfor %}

templates/payments/managePaymentPartialList.html
{% for payment in payments %}
<tr>
  <td class="text-center">{{payment.number}}</td>
  <td class="text-center">{{payment.paymentDate}}</td>
  <td class="text-center">{{payment.paymentType}}</td>
  <td class="text-center">{{payment.item}}</td>
  <td class="text-center">{{payment.price}}</td>
  <td class="text-center">{{payment.note}}</td>
  <td>
      <button type="button"
              class="btn btn-warning btn-xs js-update-payment"
              url="{% url 'dashboard:managePaymentUpdate' %}" data-id="{{payment.number}}">
        <span class="glyphicon glyphicon-pencil"></span> 수정
      </button>
      <button type="button"
              class="btn btn-danger btn-xs js-delete-payment"
              url="{% url 'dashboard:managePaymentDelete' %}" data-id="{{payment.number}}">
        <span class="glyphicon glyphicon-trash"></span> 삭제
      </button>      
  </td>
</tr>
{% empty %}
<tr>
  <td colspan="8" class="text-center bg-warning">No Data</td>
</tr>
{% endfor %}

templates/payments/managePaymentPartialUpdate.html
<form method="post" action="{% url 'dashboard:managePaymentUpdateForm' %}" class="js-payment-update-form">
  {% csrf_token %}
  <div class="modal-header">
    <input class="hidden" name="number" value="{{payment.number}}">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">결제정보 수정</h4>
  </div>
  <div class="modal-body">
    {% include 'payments/managePaymentPartialForm.html' %}
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">취소</button>
    <button type="submit" class="btn btn-primary">저장</button>
  </div>
</form>

templates/payments/managePaymentStudentList.html
{% for student in students %}
<tr>
  <td class="text-center">{{student.number}}</td>
  <td class="text-center">{{student.stname}}</td>
  <td class="text-center">{{student.contact}}</td>
  <td class="text-center">{{student.school}}</td>
  <td class="text-center">{{student.years}}</td>
  <td>
      <button type="button"
              class="btn btn-warning btn-xs" id="js-inquire-payment"
              url="{% url 'dashboard:managePaymentInquire' %}" data-id="{{student.number}}">
        <span class="glyphicon glyphicon-pencil"></span> 조회
      </button>
      <button type="button"
              class="btn btn-danger btn-xs js-register-payment"
              url="{% url 'dashboard:managePaymentCreate' %}" data-id="{{student.number}}">
        <span class="glyphicon glyphicon-send"></span> 등록
      </button>
  </td>
</tr>
{% empty %}
<tr>
  <td colspan="8" class="text-center bg-warning">No Data</td>
</tr>
{% endfor %}