adminbase/urls.py
'''
	admin urls
'''
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	#admin에서 include로 바로 넘기기에 로그인 기능등 모든 기능은 dashboard에서 이루어져야 함
    url(r'^', include('dashboard.urls', namespace='dashboard')),
    url(r'^admin/', include(admin.site.urls)),
]

dashboard/urls.py
from django.conf.urls import url, include
from . import views
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    # sb-admin components urls
    url(r'^blank/$', views.BlankView.as_view(), name="blank"),
    url(r'^buttons/$', views.ButtonsView.as_view(), name="buttons"),
    url(r'^flot/$', views.FlotView.as_view(), name="flot"),
    url(r'^forms/$', views.FormsView.as_view(), name="forms"),
    url(r'^grid/$', views.GridView.as_view(), name="grid"),
    url(r'^icons/$', views.IconsView.as_view(), name="icons"),
    url(r'^morris/$', views.MorrisView.as_view(), name="morris"),
    url(r'^notifications/$', views.NotificationsView.as_view(), name="notifications"),
    url(r'^panels/$', views.PanelsView.as_view(), name="panels"),
    url(r'^tables/$', views.TablesView.as_view(), name="tables"),
    url(r'^typography/$', views.TypographyView.as_view(), name="typography"),

    # app urls
    url(r'^$', auth_views.login, {'template_name': 'components/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'template_name': 'components/logout.html'}, name='logout'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^setting/$', views.setting, name='setting'),
    url(r'^index/$', login_required(views.IndexView.as_view()), name="index"),    
    url(r'^create/$', login_required(views.NoticeView.create), name='noticeCreate'),
    url(r'^delete/$', login_required(views.NoticeView.deleteButton), name='noticeDelete'),
    url(r'^delete2/$', login_required(views.NoticeView.deleteForm), name='noticeDelete2'),
    url(r'^createPayment/$', login_required(views.DashPaymentView.createPayment), name='dashboardPayment'),
    url(r'^createPayment/Form/$', login_required(views.DashPaymentView.createPaymentForm), name='dashboardPaymentCreate'),    
    url(r'^error/$', login_required(views.ErrorView.as_view()), name='error'),

    url(r'^students/', include('students.urls')),
    url(r'^attendance/', include('attendance.urls')),
    url(r'^payments/', include('payments.urls')),
    url(r'^lessons/', include('lessons.urls')),
    url(r'^sales/', include('sales.urls')),
]

lessons/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    # put your urls
    url(r'^manageLesson/$', login_required(views.LessonManageView.show), name="manageLessonShow"),
    url(r'^manageLesson/create/$', login_required(views.LessonCreateView.create), name="manageLessonCreate"),
    url(r'^manageLesson/(?P<pk>\d+)/update/$', login_required(views.LessonManageView.update), name='manageLessonUpdate'),
    url(r'^manageLesson/(?P<pk>\d+)/delete/$', login_required(views.LessonManageView.delete), name='manageLessonDelete'),
    url(r'^managePayment/student/(?P<pk>\d+)/inquire/$', login_required(views.LessonManageView.inquire), name='managePaymentStudentInquire'),
    url(r'^managePayment/student/(?P<pk>\d+)/delete/$', login_required(views.LessonManageView.deleteStudentLesson), name='managePaymentStudentDelete'),     
]

payments/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    # put your urls
    url(r'^$', login_required(views.PaymentManageView.show), name='managePaymentShow'),
    url(r'^search/$', login_required(views.PaymentManageView.search), name='managePaymentSearch'),  
    url(r'^inquire/$', login_required(views.PaymentManageView.inquire), name='managePaymentInquire'),  
    url(r'^create/$', login_required(views.PaymentManageView.create), name='managePaymentCreate'),
    url(r'^createForm/$', login_required(views.PaymentManageView.createForm), name='managePaymentCreateForm'),     
    url(r'^update/$', login_required(views.PaymentManageView.update), name='managePaymentUpdate'),
    url(r'^updateForm/$', login_required(views.PaymentManageView.updateForm), name='managePaymentUpdateForm'),
    url(r'^delete/$', login_required(views.PaymentManageView.delete), name='managePaymentDelete'),
    url(r'^deleteForm/$', login_required(views.PaymentManageView.deleteForm), name='managePaymentDeleteForm'),    
]

sales/urls.py
'''
    urls is to be connect view 
'''
from django.conf.urls import url
from . import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    # manage student urls
    url(r'^display/$', login_required(views.daySalesView.display), name="salesDisplay"),
    url(r'^display/makeDay/$', login_required(views.daySalesView.makeDay), name='salesCreateDay'),
    url(r'^display/inquire/$', login_required(views.daySalesView.inquire), name='salesInquire'),
    url(r'^display/monthSales/$', login_required(views.motnthSaleView.as_view()), name='monthSales'),
]

students/urls.py
'''
    urls is to be connect view 
'''
from django.conf.urls import url
from . import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    # manage student urls
    url(r'^$', login_required(views.StudentView.display), name="studentDisplay"),
    url(r'^create/$', login_required(views.StudentCreateView.create), name='studentCreate'),
    url(r'^update/$', login_required(views.StudentView.update), name='studentUpdate'),
    url(r'^updateForm/$', login_required(views.StudentView.updateForm), name='studentUpdateForm'),
    url(r'^delete/$', login_required(views.StudentView.delete), name='studentDelete'),
    url(r'^deleteForm/$', login_required(views.StudentView.deleteForm), name='studentDeleteForm'),
    
    # manage schedule table urls
    url(r'^studentSchedule/$', login_required(views.ScheduleView.display), name='scheduleDisplay'),
    # this is about getting data from web with request.get 
    #url(r'^studentClassSchedule/(?P<pk>\d+)/test/$', views.ClassSchedule.test, name='test'),
    #url(r'^studentClassSchedule/(?P<slug>[-\w]+)/test/$', views.ClassSchedule.test, name='test'),
    url(r'^studentSchedule/updateSchedule/$', login_required(views.ScheduleView.update), name='scheduleUpdate'),
    url(r'^studentSchedule/attendLesson/$', login_required(views.ScheduleView.attendLesson), name='attendLesson'),
    
    # manage student's lesson table urls
    url(r'^lessonTable/$', login_required(views.LessonTableView.displayAttendList), name='lessonTable'),
    url(r'^lessonTable/search/$', login_required(views.LessonTableView.searchStudent), name='lessonTableSearch'),
    url(r'^lessonTable/display/$', login_required(views.LessonTableView.display), name='lessonTableDisplay'),
    url(r'^lessonTable/create/$', login_required(views.LessonTableView.create), name='lessonTableCreate'),
    url(r'^lessonTable/completeFillOut/$', login_required(views.LessonTableView.completeFillout), name='lessonTableFillout'),
    url(r'^lessonTable/update/$', login_required(views.LessonTableView.update), name='lessonTableUpdate'),
    url(r'^lessonTable/selectSheet/$', login_required(views.LessonTableView.getSheet), name='LessonSelectSheet'),
    url(r'^lessonTable/checkPayment/$', login_required(views.LessonTableView.payment), name='lessonTablePayment'),
]

templates/components/blank.html
{% extends "dashboard/base.html" %}


{% block content %}

<h1 class="page-header">Blank</h1>
    
{% endblock content %}

templates/components/error.html
{% extends "dashboard/base.html" %}
{% load staticfiles %}
{% block extrahead %}
<link href="{% static 'custom/css/error.css' %}" rel="stylesheet">
{% endblock extrahead %}
{% block content %}
<div class="container bootstrap snippet">
    <div class="row">
        <div class="col-md-12">
            <div class="pull-right" style="margin-top:10px;">
                <div class="col-md-10 col-md-offset-1 pull-right">
                    <img class="img-error" src="https://bootdey.com/img/Content/fdfadfadsfadoh.png">
                    <h2>404 Not Found</h2>
                    <p>Sorry, an error has occured, Requested page not found!</p>
                    <h2>Error Message</h2>
                    <p>{{errorMsg}}</p>
                    <div class="error-actions">
                        <a href="{% url 'dashboard:index' %}" class="btn btn-primary btn-lg">
                            <span class="glyphicon glyphicon-arrow-left"></span>
                            Back Home 
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/components/index.html
<!-- Dashboard -->

{% extends "dashboard/base.html" %}
{% load staticfiles %}

{% block extrahead %}

<!-- Timeline CSS -->
<link href="{% static 'dist/css/timeline.css' %}" rel="stylesheet">

<!-- Morris Charts CSS -->
<link href="{% static 'bower_components/morrisjs/morris.css' %}" rel="stylesheet">

{% endblock extrahead %}


{% block content %}
    
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Home<small> 좋은 하루 되세요!</small></h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
{% if is_valid %}
<div class="row">
    <div class="col-lg-3 col-md-6">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-user fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge">{{payment_students}}</div>
                        <div>결제일 회원수</div>
                    </div>
                </div>
            </div>
            <a href="{% url 'dashboard:managePaymentShow' %}">
                <div class="panel-footer">
                    <span class="pull-left">결제 페이지로 이동</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>
    <div class="col-lg-3 col-md-6">
        <div class="panel panel-green">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-users fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge">수업</div>
                    </div>
                </div>
            </div>
            <a href="{% url 'dashboard:manageLessonShow' %}">
                <div class="panel-footer">
                    <span class="pull-left">수업관리로 이동</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>
    <div class="col-lg-2 col-md-6">
        <div class="panel panel-yellow">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-linkedin fa-4x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge">{{human_students}}</div>
                        <div>휴먼 회원수</div>
                    </div>
                </div>
            </div>
            <a href="{% url 'dashboard:studentDisplay' %}">
                <div class="panel-footer">
                    <span class="pull-left">회원관리로 이동</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>
    <div class="col-lg-4 col-md-6">
        <div class="panel panel-red">
            <div class="panel-heading">
                <div class="row">
                    <div class="col-xs-3">
                        <i class="fa fa-won fa-5x"></i>
                    </div>
                    <div class="col-xs-9 text-right">
                        <div class="huge">{{total_todaySales}}</div>
                        <div>오늘 매출액</div>
                    </div>
                </div>
            </div>
            <a href="{% url 'dashboard:salesDisplay' %}">
                <div class="panel-footer">
                    <span class="pull-left">매출관리로 이동</span>
                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                    <div class="clearfix"></div>
                </div>
            </a>
        </div>
    </div>
</div>
<!-- /.row -->
<div class="row">
    <div class="col-lg-4 col-md-4">
        <div class="box box-info">
            <div class="box-header with-border">
                <h3 class="box-title">오늘 출석자</h3>
            </div>
            <div class="box-body table-responsive no-padding">       
                <table class="table table-striped table-bordered table-hover">
                    <thead>
                        <tr>
                            <th width="15%">회원번호</th>
                            <th width="15%">이름</th>
                            <th width="35%">연락처</th>
                            <th width="15%">차트작성</th>
                        </tr>
                    </thead>
                    <tbody>
                        {{attendanceList}}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="col-lg-8 col-md-8" id="notice-div">
        <div class="box box-danger">
            <div class="box-header with-border">
                <div class="row">
                    <div class="col-lg-2 col-md-2">
                        <h3 class="box-title">공지사항</h3>
                    </div>
                    <div class="col-lg-3 col-md-3">
                        <button class="btn btn-primary btn-xs js-register-notice" data-url="{% url 'dashboard:noticeCreate' %}">추가</button>
                    </div>
                </div>
            </div>         
            <div class="box-body table-responsive no-padding">       
                <table class="table table-striped table-bordered table-hover" id="notice-table">
                    <thead>
                        <tr>
                            <th width="2%">No.</th>
                            <th width="8%">작성자</th>
                            <th>내용</th>
                            <th width="2%">/</th>
                        </tr>
                    </thead>
                    <tbody>
                        {{noticeList}}
                    </tbody>
                </table>
            </div>
        </div>
    </div>  
</div>
<div class="row">
    <div class="col-lg-6 col-md-6">
        <div class="box box-info">
            <div class="box-header with-border">
                <h3 class="box-title">결제해야되는 회원</h3>
            </div>            
            <div class="box-body table-responsive no-padding">       
                <table class="table table-striped table-bordered table-hover" id="payment-table">
                    <thead>
                        <tr>
                            <th>회원번호</th>
                            <th>이름</th>
                            <th>연락처</th>
                            <th>학교</th>
                            <th>학년</th>
                            <th width="2%">/</th>
                        </tr>
                    </thead>
                    <tbody>
                        {{paymentList}}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <!--<div class="col-lg-6 col-md-6">
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">수업초과한 회원</h3>
            </div>            
            <div class="box-body table-responsive no-padding">       
                <table class="table table-striped table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>No.</th>
                            <th>이름</th>
                            <th>연락처</th>
                            <th>학교</th>
                            <th>학년</th>
                            <th width="2%">/</th>
                        </tr>
                    </thead>
                    <tbody>
                        {{exceedList}}
                    </tbody>
                </table>
            </div>
        </div>
    </div>-->
    <div class="col-lg-6 col-md-6">
        <div class="box box-success">
            <div class="box-header with-border">
                <h3 class="box-title">오늘 결제 내역</h3>
            </div>            
            <div class="box-body table-responsive no-padding">       
                <table class="table table-striped table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>No.</th>
                            <th>수업/상품</th>
                            <th>가격</th>
                            <th>결제방식</th>
                            <th>결제상태</th>
                            <th>이름</th>
                        </tr>
                    </thead>
                    <tbody>
                        {{todaySales}}
                    </tbody>
                </table>
            </div>
        </div>
    </div>      
</div>

<!--<div class="row">
    <div class="col-lg-6 col-md-6">
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">오늘 결제 내역</h3>
            </div>            
            <div class="box-body table-responsive no-padding">       
                <table class="table table-striped table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>No.</th>
                            <th>수업/상품</th>
                            <th>가격</th>
                            <th>결제방식</th>
                            <th>결제상태</th>
                            <th>이름</th>
                        </tr>
                    </thead>
                    <tbody>
                        {{todaySales}}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% else %}
<div class="row">
    <h1> {{errorMsg}} </h1>
</div>-->
{% endif %}
<!-- THE MODAL WE WILL BE USING -->
<div class="modal fade" id="modal-dashboard">
    <div class="modal-dialog">
        <div class="modal-content"></div>
    </div>
</div>
<div class="modal fade" id="modal-dashboard-payment">
    <div class="modal-dialog">
        <div class="modal-content"></div>
    </div>
</div>
{% endblock content %}


{% block extrajs %}

<!-- Morris Charts JavaScript -->
<script src="{% static 'js/dashboard.js' %}"></script>
<script src="{% static 'bower_components/raphael/raphael-min.js' %}"></script>
<script src="{% static 'bower_components/morrisjs/morris.min.js' %}"></script>

{% endblock extrajs %}

templates/components/login.html
{% extends "layout/base.html" %}
{% load staticfiles %}
{% block extrastyle %}
<link href="{% static 'custom/css/loginBackground.css' %}" rel="stylesheet">
{% endblock extrastyle %}
{% block basecontent %}
<div class="container">
    <div class="row" id="login-header">
        <img src="{% static 'image/background.png' %}" class="img-fluid logo" alt="logo">
        <div class="col-md-4 col-md-offset-4">
            <div class="login-panel panel panel-default">
                <div class="panel-heading">
                    <h5 class="panel-title text-center"><b>Private School CMS</b></h5>
                </div>
                <div class="panel-body">
                    <form method='post' role="form" id="login-form">
                        {% csrf_token %}
                        <fieldset>
                            <div class="form-group">
                                <label for="{{ form.username.id_for_label }}">ID</label> 
                                <input class="form-control" id="{{ form.username.id_for_label }}" placeholder="ID" maxlength="15" name="{{ form.username.html_name }}" type="text" />
                            </div>
                            <div class="form-group">
                                <label for="{{ form.password.id_for_label }}">Password</label>
                                <input class="form-control" id="{{ form.password.id_for_label }}" placeholder="Password" maxlength="120" name="{{ form.password.html_name }}" type="password" />
                            </div>
                            {% if form.errors %}
                            <h3 class=" label label-danger">
                                아이디또는 비밀번호가 일치하지 않습니다.
                            </h3>
                            {% endif %}
                            <br>
                            <br>                            
                            <!-- Change this to a button or input when using this as a form -->
                            <button type="submit" class="btn btn-lg btn-success btn-block">Login</button>
                        </fieldset>
                    </form>
                    <br>
                    <a href="{% url 'dashboard:signup' %}">새로운 계정을 생성하겠습니다.</a>
                </div>

            </div>
        </div>
    </div>
</div>

{% endblock basecontent %}

templates/components/morris.html
{% extends "dashboard/base.html" %}
{% load staticfiles %}

{% block extrahead %}
    
<!-- Morris Charts CSS -->
<link href="{% static 'bower_components/morrisjs/morris.css' %}" rel="stylesheet">

{% endblock extrahead %}


{% block content %}
    
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Morris.js Charts</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<div class="row">
    <div class="col-lg-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                Area Chart Example
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div id="morris-area-chart"></div>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-6 -->
    <div class="col-lg-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                Bar Chart Example
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div id="morris-bar-chart"></div>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-6 -->
    <div class="col-lg-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                Line Chart Example
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div id="morris-line-chart"></div>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-6 -->
    <div class="col-lg-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                Donut Chart Example
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div id="morris-donut-chart"></div>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-6 -->
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Morris.js Usage
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <p>Morris.js is a jQuery based charting plugin created by Olly Smith. In SB Admin, we are using the most recent version of Morris.js which includes the resize function, which makes the charts fully responsive. The documentation for Morris.js is available on their website, <a target="_blank" href="http://morrisjs.github.io/morris.js/">http://morrisjs.github.io/morris.js/</a>.</p>
                <a target="_blank" class="btn btn-default btn-lg btn-block" href="http://morrisjs.github.io/morris.js/">View Morris.js Documentation</a>
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-6 -->
</div>
<!-- /.row -->

{% endblock content %}


{% block extrajs %}

<!-- Morris Charts JavaScript -->
<script src="{% static 'bower_components/raphael/raphael-min.js' %}"></script>
<script src="{% static 'bower_components/morrisjs/morris.min.js' %}"></script>
<script src="{% static 'js/morris-data.js' %}"></script>

{% endblock extrajs %}

templates/components/setting.html
{% extends "dashboard/base.html" %}
{% load staticfiles %}
{% load widget_tweaks %}

{% block content %}
<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <div class="login-panel panel panel-default">
            <div class="panel-heading">
                <h5 class="panel-title text-center"><b>사용자 정보 변경</b></h5>
            </div>
            <div class="panel-body">
               <form method="post">
                {% csrf_token %}
                <fieldset>
                    {% for field in form %}
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {% render_field field class="form-control" %}<br>    
                        {% for error in field.errors %}
                        <p style="color: red">{{ error }}</p>
                        {% endfor %}
                    {% endfor %}
                </fieldset>
                <button type="submit" class="btn btn-lg btn-success btn-block">수정하기</button><br>
                <a href="{% url 'dashboard:index' %}"><button type="button" class="btn btn-lg btn-danger btn-block">Cancel</button></a>
            </form>
        </div>

    </div>
</div>
</div>
{% endblock content %}

templates/components/signup.html
{% extends "layout/base.html" %}
{% load widget_tweaks %}

{% block basecontent %}
<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
                <div class="login-panel panel panel-default">
                    <div class="panel-heading">
                        <h5 class="panel-title text-center"><b>Sign up</b></h5>
                    </div>
                    <div class="panel-body">
                        <form method="post">
                            {% csrf_token %}
                            <fieldset>
                                {% for field in form %}
                                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                {% render_field field class="form-control" placeholder=field.help_text %}<br>    
                                {% for error in field.errors %}
                                <p style="color: red">{{ error }}</p>
                                {% endfor %}
                                {% endfor %}
                            </fieldset>
                            <button type="submit" class="btn btn-lg btn-success btn-block">Sign up</button><br>
                            <a href="{% url 'dashboard:login' %}"><button type="button" class="btn btn-lg btn-danger btn-block  ">Cancel</button></a>
                        </form>
                    </div>
                </div>
        </div>
    </div>
</div>

{% endblock basecontent %}