adminbase/urls.py
'''
	admin urls
'''
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	#admin에서 include로 바로 넘기기에 로그인 기능등 모든 기능은 dashboard에서 이루어져야 함
    url(r'^', include('dashboard.urls', namespace='dashboard')),
    url(r'^admin/', include(admin.site.urls)),
]

attendance/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^$', login_required(views.AttendanceView.searchStudent), name="attendanceSearch"),
    url(r'^attendanceList/$', login_required(views.AttendanceView.getAttendList), name="getAttendList"),
    url(r'^attendanceList/registerCard/$', login_required(views.AttendanceView.registerCardNumber), name="registerAttendanceCard"),
    url(r'^attendanceList/tagCard/$', login_required(views.AttendanceView.tagStudentAttendance), name="tagAttendanceCard"),
    url(r'^attendanceList/stopTagCard/$', login_required(views.AttendanceView.stopTagStudentAttendance), name="stopTagStudentAttendance"),
    url(r'^(?P<pk>\d+)/update/$', login_required(views.AttendanceView.update), name="attendanceUpdate"),
]

dashboard/urls.py
from django.conf.urls import url, include
from . import views
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    # sb-admin components urls
    url(r'^blank/$', views.BlankView.as_view(), name="blank"),
    url(r'^buttons/$', views.ButtonsView.as_view(), name="buttons"),
    url(r'^flot/$', views.FlotView.as_view(), name="flot"),
    url(r'^forms/$', views.FormsView.as_view(), name="forms"),
    url(r'^grid/$', views.GridView.as_view(), name="grid"),
    url(r'^icons/$', views.IconsView.as_view(), name="icons"),
    url(r'^morris/$', views.MorrisView.as_view(), name="morris"),
    url(r'^notifications/$', views.NotificationsView.as_view(), name="notifications"),
    url(r'^panels/$', views.PanelsView.as_view(), name="panels"),
    url(r'^tables/$', views.TablesView.as_view(), name="tables"),
    url(r'^typography/$', views.TypographyView.as_view(), name="typography"),

    # app urls
    url(r'^$', auth_views.login, {'template_name': 'components/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'template_name': 'components/logout.html'}, name='logout'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^setting/$', views.setting, name='setting'),
    url(r'^index/$', login_required(views.IndexView.as_view()), name="index"),    
    url(r'^create/$', login_required(views.NoticeView.create), name='noticeCreate'),
    url(r'^delete/$', login_required(views.NoticeView.deleteButton), name='noticeDelete'),
    url(r'^delete2/$', login_required(views.NoticeView.deleteForm), name='noticeDelete2'),
    url(r'^createPayment/$', login_required(views.DashPaymentView.createPayment), name='dashboardPayment'),
    url(r'^createPayment/Form/$', login_required(views.DashPaymentView.createPaymentForm), name='dashboardPaymentCreate'),    
    url(r'^error/$', login_required(views.ErrorView.as_view()), name='error'),

    url(r'^students/', include('students.urls')),
    url(r'^attendance/', include('attendance.urls')),
    url(r'^payments/', include('payments.urls')),
    url(r'^lessons/', include('lessons.urls')),
    url(r'^sales/', include('sales.urls')),
]

lessons/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    # put your urls
    url(r'^manageLesson/$', login_required(views.LessonManageView.show), name="manageLessonShow"),
    url(r'^manageLesson/create/$', login_required(views.LessonCreateView.create), name="manageLessonCreate"),
    url(r'^manageLesson/(?P<pk>\d+)/update/$', login_required(views.LessonManageView.update), name='manageLessonUpdate'),
    url(r'^manageLesson/(?P<pk>\d+)/delete/$', login_required(views.LessonManageView.delete), name='manageLessonDelete'),
    url(r'^managePayment/student/(?P<pk>\d+)/inquire/$', login_required(views.LessonManageView.inquire), name='managePaymentStudentInquire'),
    url(r'^managePayment/student/(?P<pk>\d+)/delete/$', login_required(views.LessonManageView.deleteStudentLesson), name='managePaymentStudentDelete'),     
]

payments/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    # put your urls
    url(r'^$', login_required(views.PaymentManageView.show), name='managePaymentShow'),
    url(r'^search/$', login_required(views.PaymentManageView.search), name='managePaymentSearch'),  
    url(r'^inquire/$', login_required(views.PaymentManageView.inquire), name='managePaymentInquire'),  
    url(r'^create/$', login_required(views.PaymentManageView.create), name='managePaymentCreate'),
    url(r'^createForm/$', login_required(views.PaymentManageView.createForm), name='managePaymentCreateForm'),     
    url(r'^update/$', login_required(views.PaymentManageView.update), name='managePaymentUpdate'),
    url(r'^updateForm/$', login_required(views.PaymentManageView.updateForm), name='managePaymentUpdateForm'),
    url(r'^delete/$', login_required(views.PaymentManageView.delete), name='managePaymentDelete'),
    url(r'^deleteForm/$', login_required(views.PaymentManageView.deleteForm), name='managePaymentDeleteForm'),    
]

sales/urls.py
'''
    urls is to be connect view 
'''
from django.conf.urls import url
from . import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    # manage student urls
    url(r'^display/$', login_required(views.daySalesView.display), name="salesDisplay"),
    url(r'^display/makeDay/$', login_required(views.daySalesView.makeDay), name='salesCreateDay'),
    url(r'^display/inquire/$', login_required(views.daySalesView.inquire), name='salesInquire'),
    url(r'^display/monthSales/$', login_required(views.motnthSaleView.as_view()), name='monthSales'),
]

students/urls.py
'''
    urls is to be connect view 
'''
from django.conf.urls import url
from . import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    # manage student urls
    url(r'^$', login_required(views.StudentView.display), name="studentDisplay"),
    url(r'^create/$', login_required(views.StudentCreateView.create), name='studentCreate'),
    url(r'^update/$', login_required(views.StudentView.update), name='studentUpdate'),
    url(r'^updateForm/$', login_required(views.StudentView.updateForm), name='studentUpdateForm'),
    url(r'^delete/$', login_required(views.StudentView.delete), name='studentDelete'),
    url(r'^deleteForm/$', login_required(views.StudentView.deleteForm), name='studentDeleteForm'),
    
    # manage schedule table urls
    url(r'^studentSchedule/$', login_required(views.ScheduleView.display), name='scheduleDisplay'),
    # this is about getting data from web with request.get 
    #url(r'^studentClassSchedule/(?P<pk>\d+)/test/$', views.ClassSchedule.test, name='test'),
    #url(r'^studentClassSchedule/(?P<slug>[-\w]+)/test/$', views.ClassSchedule.test, name='test'),
    url(r'^studentSchedule/updateSchedule/$', login_required(views.ScheduleView.update), name='scheduleUpdate'),
    url(r'^studentSchedule/attendLesson/$', login_required(views.ScheduleView.attendLesson), name='attendLesson'),
    
    # manage student's lesson table urls
    url(r'^lessonTable/$', login_required(views.LessonTableView.displayAttendList), name='lessonTable'),
    url(r'^lessonTable/search/$', login_required(views.LessonTableView.searchStudent), name='lessonTableSearch'),
    url(r'^lessonTable/display/$', login_required(views.LessonTableView.display), name='lessonTableDisplay'),
    url(r'^lessonTable/create/$', login_required(views.LessonTableView.create), name='lessonTableCreate'),
    url(r'^lessonTable/completeFillOut/$', login_required(views.LessonTableView.completeFillout), name='lessonTableFillout'),
    url(r'^lessonTable/update/$', login_required(views.LessonTableView.update), name='lessonTableUpdate'),
    url(r'^lessonTable/selectSheet/$', login_required(views.LessonTableView.getSheet), name='LessonSelectSheet'),
    url(r'^lessonTable/checkPayment/$', login_required(views.LessonTableView.payment), name='lessonTablePayment'),
]

dashboard/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.
class Notice(models.Model):
	number = models.IntegerField(default=0, unique=True, verbose_name="작성번호", help_text='숫자만 입력하세요.')
	text = models.CharField(max_length=150, default='', verbose_name="내용", help_text='120자 이내로 입력하세요.')
	writer = models.CharField(max_length=20, default='', verbose_name='작성자', help_text='작성자를 입력하세요.')

	def __str__(self):
		return '['+self.writer+']의 공지사항'

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    fileName = models.FilePathField(path='tutor_excel/', verbose_name="강사시간표 파일명")

@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

dashboard/forms.py
from django import forms
from .models import Notice
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
	username = forms.CharField(max_length=10, required=True, help_text='영문 10자로 입력하세요.', label='아이디')
	password1 = forms.CharField(max_length=12, widget=forms.PasswordInput, label='비밀번호', help_text='최대 12자로 입력하세요.')
	password2 = forms.CharField(max_length=12, widget=forms.PasswordInput, label='비밀번호 확인', help_text='비밀번호 확인')
	first_name = forms.CharField(max_length=8, required=True, help_text='길동', label='이름')
	last_name = forms.CharField(max_length=4, required=True, help_text='홍', label='성')
	fileName = forms.FilePathField(path='tutor_excel/', label="강사시간표 파일명")
	class Meta:
		model = User
		fields = ('username', 'password1', 'password2', 'first_name', 'last_name','fileName')

class UpdateForm(UserCreationForm):
	password1 = forms.CharField(max_length=12, widget=forms.PasswordInput, label='이전 비밀번호', help_text='최대 12자로 입력하세요.')
	password2 = forms.CharField(max_length=12, widget=forms.PasswordInput, label='이전 비밀번호 확인', help_text='비밀번호 확인')
	new_password = forms.CharField(max_length=12, widget=forms.PasswordInput, label='새로운 비밀번호', help_text='최대 12자로 입력하세요.')
	first_name = forms.CharField(max_length=8, required=True, help_text='길동', label='이름')
	last_name = forms.CharField(max_length=4, required=True, help_text='홍', label='성')
	fileName = forms.FilePathField(path='tutor_excel/', label="강사시간표 파일명")
	class Meta:
		model = User
		fields = ('password1', 'password2', 'new_password', 'first_name', 'last_name','fileName')
class NoticeForm(forms.ModelForm):
	class Meta:
		model = Notice
		fields = ('number', 'text', 'writer')

templates/dashboard/base.html
<!-- 대시보드 메뉴판 설정 파일 -->

{% extends "layout/base.html" %}

{% block basecontent %}
<div id="wrapper">
    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'dashboard:index' %}">학원 관리시스템</a>
        </div>
        <!-- /.navbar-header -->

        <ul class="nav navbar-top-links navbar-right">
            <!-- /.dropdown -->
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
                </a>
                <ul class="dropdown-menu dropdown-user">
                    <li><a href="#"><i class="fa fa-user fa-fw"></i> {{loginUser}}</a>
                    </li>
                    <li><a href="#"><i class="fa fa-folder-o fa-fw"></i> {{userChartFileName}}</a>
                    </li>                    
                    <li><a href="{% url 'dashboard:setting' %}"><i class="fa fa-gear fa-fw"></i> Settings</a>
                    </li>
                    <li class="divider"></li>
                    <li><a href="{% url 'dashboard:logout' %}"><i class="fa fa-sign-out fa-fw"></i>Logout</a>
                    </li>
                </ul>
                <!-- /.dropdown-user -->
            </li>
            <!-- /.dropdown -->
        </ul>
        <!-- /.navbar-top-links -->
        <div class="navbar-default sidebar" role="navigation">
            <div class="sidebar-nav navbar-collapse">
                <ul class="nav" id="side-menu">                 
                    <li>
                        <a href="{% url 'dashboard:index' %}"><i class="fa fa-dashboard fa-fw"></i>Home</a>
                    </li>                    
                    <!--<li>
                        <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i> Charts<span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a href="{% url 'dashboard:flot' %}">Flot Charts</a>
                            </li>
                            <li>
                                <a href="{% url 'dashboard:morris' %}">Morris.js Charts</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="{% url 'dashboard:forms' %}"><i class="fa fa-edit fa-fw"></i> Forms</a>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-wrench fa-fw"></i> UI Elements<span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a href="{% url 'dashboard:panels' %}">Panels and Wells</a>
                            </li>
                            <li>
                                <a href="{% url 'dashboard:buttons' %}">Buttons</a>
                            </li>
                            <li>
                                <a href="{% url 'dashboard:notifications' %}">Notifications</a>
                            </li>
                            <li>
                                <a href="{% url 'dashboard:typography' %}">Typography</a>
                            </li>
                            <li>
                                <a href="{% url 'dashboard:icons' %}"> Icons</a>
                            </li>
                            <li>
                                <a href="{% url 'dashboard:grid' %}">Grid</a>
                            </li>
                        </ul>
                    </li>-->

                    <!-- 학생정보 추가 및 조회 -->
                    <li>
                        <a href="#"><i class="fa fa-sitemap fa-fw"></i> 회원관리<span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a href="{% url 'dashboard:studentCreate' %}">회원등록</a>
                            </li>
                            <li>
                                <a href="{% url 'dashboard:studentDisplay' %}">회원조회</a>
                            </li>
                        </ul>
                        <!-- /.nav-second-level -->
                    </li>                    
                    <li>
                        <a href="{% url 'dashboard:lessonTable' %}"><i class="fa fa-calendar-o fa-fw"></i> 회원차트</a>
                        <!-- dashboard 디렉터리에서 urls.py에 해당 html명 연결시켜줘야 함
                             그리고 views.py에서 해당 뷰 클래스 만들어야 함 -->
                    </li>
                    <li>
                        <a href="{% url 'dashboard:scheduleDisplay' %}"><i class="fa fa-list fa-fw"></i> 수업 시간표</a>
                        <!-- dashboard 디렉터리에서 urls.py에 해당 html명 연결시켜줘야 함
                             그리고 views.py에서 해당 뷰 클래스 만들어야 함 -->
                    </li>                     
                    <li>
                        <a href="{% url 'dashboard:managePaymentShow' %}"><i class="fa fa-shopping-cart fa-fw"></i> 결제관리</a>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-anchor fa-fw"></i> 수업 관리<span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a href="{% url 'dashboard:manageLessonCreate' %}">수업 등록</a>
                            </li>
                            <li>
                                <a href="{% url 'dashboard:manageLessonShow' %}">수업 조회</a>
                            </li>                                                       
                        </ul>
                        <!-- /.nav-second-level -->
                    </li>  
                    <li>
                        <a href="#"><i class="fa fa-bell fa-fw"></i> 출석 관리<span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a href="{% url 'dashboard:attendanceSearch' %}">출석 기록</a>
                            </li>
                            <li>
                                <a href="{% url 'dashboard:tagAttendanceCard' %}">출석 태그</a>
                            </li>                                                       
                        </ul>
                    </li>                                         
                    <li>
                        <a href="#"><i class="fa fa-anchor fa-fw"></i> 매출관리<span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a href="{% url 'dashboard:salesDisplay' %}">일 매출대장</a>
                            </li>                            
                            <li>
                                <a href="{% url 'dashboard:monthSales' %}">월별 매출현황</a>
                            </li>                                                       
                        </ul>
                        <!-- /.nav-second-level -->
                    </li>                                                                                                                        
                </ul>
            </div>
            <!-- /.sidebar-collapse -->
        </div>
        <!-- /.navbar-static-side -->
    </nav>


    <!-- Page Content -->
    <div id="page-wrapper">
        {% block content %}
        <!-- Your contents here -->
        {% endblock content %}
    </div>
    <footer>
        <div class="pull-right hidden-xs">
          <b>Version</b> 1.0
      </div>
      <strong>Copyright &copy;  2018-2019   Potato Smoothe </a>.</strong>  All rights reserved.
    </footer>
    <!-- /#page-wrapper -->
</div>
<!-- /#wrapper -->
{% endblock basecontent %}

templates/dashboard/noticePartialCreate.html
{% load widget_tweaks %}
<form method="post" action="{% url 'dashboard:noticeCreate' %}" class="js-notice-register-form">
  {% csrf_token %}
  <div class="modal-header" >
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">공지사항</h4>
  </div>
  <div class="modal-body">
    {% for field in form %}
    <div class="form-group{% if field.errors %} has-error{% endif %}">
      <label for="{{ field.id_for_label }}">{{ field.label }}</label>
      {% render_field field class="form-control" %}
      {% for error in field.errors %}
      <p class="help-block">{{ error }}</p>
      {% endfor %}
    </div>
    {% endfor %}
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">취소</button>
    <button type="submit" class="btn btn-primary">등록</button>
  </div>
</form>

templates/dashboard/noticePartialDelete.html
<form method="post" action="{% url 'dashboard:noticeDelete2' %}" class="js-notice-delete-form">
  {% csrf_token %}
  <input class="hidden" name="number" value="{{notice}}">
  <div class="modal-danger modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">공지사항 삭제</h4>
  </div>
  <div class="modal-body">
    <p class="lead">정말 삭제하시겠습니까?</p>
  </div>
  <div class="modal-danger modal-footer">
    <button type="submit" class="btn btn-danger">예</button>
    <button type="button" class="btn btn-default" data-dismiss="modal">아니요</button>
  </div>
</form>

templates/dashboard/notice_attendance.html
{% for attendance in attendanceList %}
<tr>
  <td>{{attendance.student.number}}</td>
  <td>{{attendance.student.stname}}</td>
  <td>{{attendance.student.contact}}</td>
  <td>{{attendance.fillOut}}</td>
</tr>
{% empty %}
<tr>
  <td colspan="8" class="text-center bg-warning">No Data</td>
</tr>
{% endfor %}

templates/dashboard/notice_notification.html
{% for notice in noticeList %}
<tr>
  <td>{{notice.number}}</td>
  <td>{{notice.writer}}</td>
  <td>{{notice.text}}</td>
  <td>
      <button type="button"
              class="btn btn-danger btn-xs js-delete-notice" url="{% url 'dashboard:noticeDelete' %}">
        <span class="glyphicon glyphicon-trash"></span> 삭제
      </button>
  </td>
</tr>
{% empty %}
<tr>
  <td colspan="8" class="text-center bg-warning">No Data</td>
</tr>
{% endfor %}

templates/dashboard/notice_paymentStudent.html
{% for student in paymentList %}
<tr>
  <td>{{student.number}}</td>
  <td>{{student.stname}}</td>
  <td>{{student.contact}}</td>
  <td>{{student.school}}</td>
  <td>{{student.years}}</td>
  <td>
      <button type="button"
              class="btn btn-warning btn-xs js-register-payment" url="{% url 'dashboard:dashboardPayment' %}">
        <span class="glyphicon glyphicon-pencil"></span> 결제
      </button>
  </td>  
</tr>
{% empty %}
<tr>
  <td colspan="8" class="text-center bg-warning">No Data</td>
</tr>
{% endfor %}

templates/dashboard/notice_paymentStudent2.html
{% for student in exceedList %}
<tr>
  <td>{{student.number}}</td>
  <td>{{student.stname}}</td>
  <td>{{student.contact}}</td>
  <td>{{student.school}}</td>
  <td>{{student.yearst}}</td>
  <td>
      <button type="button"
              class="btn btn-warning btn-xs js-update-lesson">
        <span class="glyphicon glyphicon-pencil"></span> 결제
      </button>
  </td>  
</tr>
{% empty %}
<tr>
  <td colspan="8" class="text-center bg-warning">No Data</td>
</tr>
{% endfor %}

templates/dashboard/notice_payments.html
{% for payment in todaySales %}
<tr>
  <td>{{payment.number}}</td>
  <td>{{payment.item}}</td>
  <td>{{payment.price}}</td>
  <td>{{payment.paymentType}}</td>
  <td>{{payment.paymentState}}</td>
  <td>{{payment.student.stname}}</td>
</tr>
{% empty %}
<tr>
  <td colspan="8" class="text-center bg-warning">No Data</td>
</tr>
{% endfor %}

templates/dashboard/paymentPartialCreate.html
{% load widget_tweaks %}
<form method="post" action="{% url 'dashboard:dashboardPaymentCreate' %}" class="js-payment-register-form">
  {% csrf_token %}
  <div class="modal-header" >
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">결제하기</h4>
  </div>
  <div class="modal-body">
    {% for field in form %}
    <div class="form-group{% if field.errors %} has-error{% endif %}">
      <label for="{{ field.id_for_label }}">{{ field.label }}</label>
      {% render_field field class="form-control" placeholder=field.help_text %}
      {% for error in field.errors %}
      <p class="help-block">{{ error }}</p>
      {% endfor %}
    </div>
    {% endfor %}
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">취소</button>
    <button type="submit" class="btn btn-primary">등록</button>
  </div>
</form>