adminbase/urls.py
'''
	admin urls
'''
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	#admin에서 include로 바로 넘기기에 로그인 기능등 모든 기능은 dashboard에서 이루어져야 함
    url(r'^', include('dashboard.urls', namespace='dashboard')),
    url(r'^admin/', include(admin.site.urls)),
]

lessons/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    # put your urls
    url(r'^manageLesson/$', login_required(views.LessonManageView.show), name="manageLessonShow"),
    url(r'^manageLesson/create/$', login_required(views.LessonCreateView.create), name="manageLessonCreate"),
    url(r'^manageLesson/(?P<pk>\d+)/update/$', login_required(views.LessonManageView.update), name='manageLessonUpdate'),
    url(r'^manageLesson/(?P<pk>\d+)/delete/$', login_required(views.LessonManageView.delete), name='manageLessonDelete'),
    url(r'^managePayment/student/(?P<pk>\d+)/inquire/$', login_required(views.LessonManageView.inquire), name='managePaymentStudentInquire'),
    url(r'^managePayment/student/(?P<pk>\d+)/delete/$', login_required(views.LessonManageView.deleteStudentLesson), name='managePaymentStudentDelete'),     
]

sales/urls.py
'''
    urls is to be connect view 
'''
from django.conf.urls import url
from . import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    # manage student urls
    url(r'^display/$', login_required(views.daySalesView.display), name="salesDisplay"),
    url(r'^display/makeDay/$', login_required(views.daySalesView.makeDay), name='salesCreateDay'),
    url(r'^display/inquire/$', login_required(views.daySalesView.inquire), name='salesInquire'),
    url(r'^display/monthSales/$', login_required(views.motnthSaleView.as_view()), name='monthSales'),
]

students/urls.py
'''
    urls is to be connect view 
'''
from django.conf.urls import url
from . import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    # manage student urls
    url(r'^$', login_required(views.StudentView.display), name="studentDisplay"),
    url(r'^create/$', login_required(views.StudentCreateView.create), name='studentCreate'),
    url(r'^update/$', login_required(views.StudentView.update), name='studentUpdate'),
    url(r'^updateForm/$', login_required(views.StudentView.updateForm), name='studentUpdateForm'),
    url(r'^delete/$', login_required(views.StudentView.delete), name='studentDelete'),
    url(r'^deleteForm/$', login_required(views.StudentView.deleteForm), name='studentDeleteForm'),
    
    # manage schedule table urls
    url(r'^studentSchedule/$', login_required(views.ScheduleView.display), name='scheduleDisplay'),
    # this is about getting data from web with request.get 
    #url(r'^studentClassSchedule/(?P<pk>\d+)/test/$', views.ClassSchedule.test, name='test'),
    #url(r'^studentClassSchedule/(?P<slug>[-\w]+)/test/$', views.ClassSchedule.test, name='test'),
    url(r'^studentSchedule/updateSchedule/$', login_required(views.ScheduleView.update), name='scheduleUpdate'),
    url(r'^studentSchedule/attendLesson/$', login_required(views.ScheduleView.attendLesson), name='attendLesson'),
    
    # manage student's lesson table urls
    url(r'^lessonTable/$', login_required(views.LessonTableView.displayAttendList), name='lessonTable'),
    url(r'^lessonTable/search/$', login_required(views.LessonTableView.searchStudent), name='lessonTableSearch'),
    url(r'^lessonTable/display/$', login_required(views.LessonTableView.display), name='lessonTableDisplay'),
    url(r'^lessonTable/create/$', login_required(views.LessonTableView.create), name='lessonTableCreate'),
    url(r'^lessonTable/completeFillOut/$', login_required(views.LessonTableView.completeFillout), name='lessonTableFillout'),
    url(r'^lessonTable/update/$', login_required(views.LessonTableView.update), name='lessonTableUpdate'),
    url(r'^lessonTable/selectSheet/$', login_required(views.LessonTableView.getSheet), name='LessonSelectSheet'),
    url(r'^lessonTable/checkPayment/$', login_required(views.LessonTableView.payment), name='lessonTablePayment'),
]

lessons/models.py
from django.db import models

# Create your models here.
class Lesson(models.Model):
	code = models.AutoField(primary_key=True, verbose_name="Merchant Code")
	item = models.CharField(max_length=10, unique=True, default='', verbose_name="수업", help_text="최대 20자까지 입력가능")
	price = models.IntegerField(default=0, verbose_name="가격", help_text="숫자만 입력하세요.")
	teacher = models.CharField(max_length=10, null=True, default='', verbose_name="강사", help_text="강사명")
	days = models.CharField(max_length=10, null=True, default='', verbose_name="수업요일", help_text="예시: 월/목")
	people = models.IntegerField(default=0, blank=True, null=True, verbose_name="수강생 수")
	def __str__(self):
		return str(self.item)+'['+str(self.price)+']원'

lessons/forms.py
from django import forms
from .models import Lesson

class LessonForm(forms.ModelForm):
 	class Meta:
 		model = Lesson
 		fields = ('code', 'item', 'price', 'teacher', 'days')

lessons/views.py
from django.views.generic import TemplateView
from django.shortcuts import render
from .models import Lesson
from .forms import LessonForm
from django.template.loader import render_to_string
from students.models import Student
from students.forms import StudentSearchForm
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse
from django.utils import timezone
# Create your views here.
class LessonManageView(TemplateView):
	def show(request):
		lessons = Lesson.objects.all()
		for lesson in lessons:
			number = lesson.student_set.all().count()
			lesson.people = number
			lesson.save()
		return render(request, 'manageGoods/manageLesson.html', {'lessons':lessons,'students':''})

	def saveLessonForm(template_name, form, request):
		html = {}
		if request.method == 'POST':
			if form.is_valid():
				form.save()
				html['form_is_valid'] = True
				lessons = Lesson.objects.all()
				html['lesson_list'] = render_to_string('manageGoods/manageLessonPartialList.html', {'lessons':lessons})
			else:
				html['form_is_valid'] = False
		context = {'form':form}
		html['html_form'] = render_to_string(template_name, context, request=request)
		return JsonResponse(html)

	def create(request):
		if request.method == 'POST':
			form = LessonForm(request.POST)
		else:
			form = LessonForm()
		return LessonManageView.saveLessonForm('manageGoods/manageLessonPartialCreate.html', form, request)

	def update(request, pk):
		lesson = get_object_or_404(Lesson, pk=pk)
		if request.method == 'POST':
			form = LessonForm(request.POST, instance=lesson)
		else:
			form = LessonForm(instance=lesson)
		return LessonManageView.saveLessonForm('manageGoods/manageLessonPartialUpdate.html', form, request)

	def delete(request, pk):
		lesson = get_object_or_404(Lesson, pk=pk)
		html = {}
		if request.method == 'POST':
			lesson.delete()
			html['form_is_valid'] = True
			lessons = Lesson.objects.all()
			html['lesson_list'] = render_to_string('manageGoods/manageLessonPartialList.html', {'lessons':lessons}
				, request=request)
		else:
			context = {'lesson':lesson}
			html['html_form'] = render_to_string('manageGoods/manageLessonPartialDelete.html', context, request=request)

		return JsonResponse(html)
	
	def inquire(request, pk):
		lesson = get_object_or_404(Lesson, pk=pk)
		html = {}
		try:
			if request.method == 'GET':
				lessons = Lesson.objects.all()
				students = lesson.student_set.all()
				html['studentList'] = render_to_string('manageGoods/manageLessonStudentPartialList.html',
					{'students':students}, request=request)
				return JsonResponse(html)
		except Exception as e:
			print("Error: "+str(e))
			return redirect('dashboard:error')
			
	def deleteStudentLesson(request, pk):
		try:
			html = {}
			if request.method == 'GET':
				student = get_object_or_404(Student, pk=pk)
				lesson = Lesson.objects.get(student=student)
				student.lesson = None
				student.save()
				lessons = Lesson.objects.all()
				students = lesson.student_set.all()	
				print(student)			
				html['studentList'] = render_to_string('manageGoods/manageLessonStudentPartialList.html',
					{'students':students}, request=request)
				return JsonResponse(html)
		except Exception as e:
			print("Error: "+str(e))
			return redirect('dashboard:error')

class LessonCreateView(TemplateView):
    def create(request):
        if request.method == 'POST':
            form = LessonForm(request.POST)
            return LessonCreateView.saveLessonForm(request, form, 'manageGoods/manageLessonPartialCreate.html')  
        else:
            form = LessonForm() 
            return render(request, 'manageGoods/manageLessonCreate.html', {'form':form})
    def saveLessonForm(request, form, template_name):
        html = {}
        if request.method == 'POST':
            if form.is_valid():
                html['form_is_valid'] = True
                form.save()
                form = LessonForm()
            else:
                html['form_is_valid'] = False   
        context = {'form':form}
        html['form_html'] = render_to_string(template_name, context, request=request)        
        return JsonResponse(html)   

templates/lessonTable/lessonTable.html
{% extends "dashboard/base.html" %}
{% load staticfiles %}

{% block extrahead %}
<link href="{% static 'custom/css/loading.min.css' %}" rel="stylesheet">
{% endblock extrahead %}

{% block content %}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">회원차트
            &nbsp<small>회원이 처음 가입한 경우 차트를 생성해주세요. </small>
        </h1>
    </div>
</div>
<div class="form-group input-group" id="student-search-div" style="width:30%">
    <input type="text" class="form-control" id="student-name-input" placeholder="회원이름을 입력하세요">
        <span class="input-group-btn">
            <button type="button" class="btn btn-default" url="{% url 'dashboard:lessonTableSearch' %}" id="student-search-btn"><i class="fa fa-search"></i></button>
        </span>    
</div>

<div class="row" id="student-div">
    <div class="col-lg-11">
        <div class="box box-info">
            <div class="box-body table-responsive no-padding">
                <table class="table table-striped table-bordered table-hover" id="student-table">
                    <thead>
                        <tr>
                            <th class="text-center">회원번호</th>
                            <th class="text-center">이름</th>
                            <th class="text-center">연락처</th>
                            <th class="text-center">학교</th>
                            <th class="text-center">학년</th>
                            <th class="text-center" width="35%">/</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% include 'lessonTable/lessonTableStudentList.html' %}
                    </tbody>
                </table>
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </div>
    <!-- /.col-lg-12 -->
</div>

<div class="row" id="lesson-table-div">
    <div class="col-lg-12">
        <h1 class="page-header" id="lesson-table-header">회원차트&nbsp<small>차트 작성후 작성완료를 클릭하세요. </small></h1>
        <div class="box box-primary">
            <div class="box-body table-responsive no-padding">
                <div class="row" style="width:70%">
                    <div class="col-xs-6 col-sm-4">
                        <select class="form-control" id="sheet-select">
                            {% include 'lessonTable/lessonTableSelect.html' %}
                        </select>
                    </div>      
                    <div class="col-xs-6 col-sm-4">
                        <button type="button" class="btn btn-primary" url="{% url 'dashboard:LessonSelectSheet' %}" id="sheet-select-btn">조회</button>
                    </div>
                </div>
                <br> 
                <table class="table table-striped table-bordered table-hover" id="lesson-table">                      
                    <thead>
                        <tr>
                            <th class="text-center" class="text-center" width="5%">차수</th>
                            <th class="text-center" class="text-center" width="10%">일자</th>
                            <th class="text-center" class="text-center">수업내용</th>
                            <th class="text-center" class="text-center" width="8%">확인</th>
                            <th class="text-center" class="text-center" width="8%">비고</th>
                            <th class="text-center" width="5%">/</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% include 'lessonTable/lessonTableList.html' %}
                    </tbody>
                </table>
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </div>
    <!-- /.col-lg-12 -->
</div>


{% endblock content %}

{% block extrajs %}
<script src="{% static 'js/lessonTable.js' %}"></script>
<!-- Loading Java Script -->
<script src="{% static 'custom/js/jquery.loading.min.js' %}"></script>
{% endblock extrajs %}

templates/lessonTable/lessonTableList.html
{% for info in table %}
<tr>
  <td>
    <input class="form-control" name="number" value="{{info.number}}" placeholder="숫자">
  </td>
  <td>
    <input class="form-control" name="date" value="{{info.date}}" placeholder="YY-MM-DD">
  </td>
  <td>
    <input class="form-control" name="content" value="{{info.content}}">
  </td>
  <td>
    <input class="form-control" name="completed" value="{{info.completed}}" placeholder="작성자">
  </td>
  <td>
    <input class="form-control" name="memo" value="{{info.memo}}">
    <input class="hidden" name="cells" value="{{info.cells}}">
    <input class="hidden" name="sheetName" value="{{info.sheetName}}">
    <input class="hidden" name="stNumber" value="{{info.stNumber}}">
  </td>
  <td>
    <button type="button" class="btn btn-warning btn-sm" id="update-table-btn" url="{% url 'dashboard:lessonTableUpdate' %}">
      <span class="glyphicon glyphicon-pencil"></span> 작성
    </button>
  </td>
</tr>
{% empty %}
<tr>
  <td colspan="8" class="text-center bg-warning">레슨 테이블 정보 없음(테이블을 생성해주세요.)</td>
</tr>
{% endfor %}

templates/lessonTable/lessonTableSelect.html
{% for sheet in worksheets %}
<option>{{sheet}}</option>
{% endfor %}

templates/lessonTable/lessonTableStudentList.html
{% for student in students %}
<tr>
  <td class="text-center">{{student.number}}</td>
  <td class="text-center">{{student.stname}}</td>
  <td class="text-center">{{student.contact}}</td>
  <td class="text-center">{{student.school}}</td>
  <td class="text-center">{{student.years}}</td>
  <td class="text-center">
    <button type="button" class="btn btn-info btn-xs" id="display-table-btn" url="{% url 'dashboard:lessonTableDisplay' %}"  data-id="{{student.number}}">
      <span class="glyphicon glyphicon-pencil"></span> 조회
    </button>
    <button type="button" class="btn btn-success btn-xs" id="create-table-btn" url="{% url 'dashboard:lessonTableCreate' %}"  data-id="{{student.number}}">
      <span class="glyphicon glyphicon-plus"></span> 차트 생성
    </button>   
    <button type="button" class="btn btn-primary btn-xs" id="fillout-table-btn" url="{% url 'dashboard:lessonTableFillout' %}"  data-id="{{student.number}}">
      <span class="glyphicon glyphicon-ok"></span> 작성완료
    </button>
    <button type="button" class="btn btn-danger btn-xs" id="check-payment-btn" url="{% url 'dashboard:lessonTablePayment' %}"  data-id="{{student.number}}">
      <span class="glyphicon glyphicon-ok"></span> 결제일 표시
    </button>             
  </td>
</tr>
{% empty %}
<tr>
  <td colspan="8" class="text-center bg-warning">출석회원 없음(출석회원을 확인해주세요)</td>
</tr>
{% endfor %}